server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # ===== STATIC ASSETS =====
    location /assets/ {
        try_files $uri =404;

        access_log off;

        expires 1y;

        add_header Cache-Control "public, immutable";
    }

    # ===== API =====
    location /api {
        proxy_pass http://xambook-backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ===== SPA FALLBACK =====
    location / {
        try_files $uri $uri/ /index.html;
    }
}